# Generated by Django 2.0.3 on 2018-04-20 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkm_app', '0002_auto_20180420_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setupuser',
            name='emails_for_help',
        ),
        migrations.AddField(
            model_name='setupuser',
            name='emails_for_help',
            field=models.ManyToManyField(help_text='select with whom you want to share knowledge', to=settings.AUTH_USER_MODEL),
        ),
    ]
