# Generated by Django 2.0.3 on 2018-04-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkm_app', '0005_auto_20180423_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupuser',
            name='email_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
