# Generated by Django 2.0.3 on 2018-05-03 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkm_app', '0006_auto_20180425_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setupuser',
            old_name='emails_for_help',
            new_name='share_KB_with',
        ),
    ]
