# Generated by Django 2.0.3 on 2018-05-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkm_app', '0007_auto_20180503_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buildkb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('knowledge_category', models.CharField(max_length=30)),
                ('knowledge', models.TextField()),
                ('keywords', models.TextField(blank=True)),
                ('share_with', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='setupuser',
            name='your_nickname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='setupuser',
            name='your_phone_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
