# Generated by Django 2.0.3 on 2018-05-07 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkm_app', '0008_auto_20180507_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setupuser',
            old_name='Designation',
            new_name='your_designation',
        ),
        migrations.RenameField(
            model_name='setupuser',
            old_name='job_level',
            new_name='your_job_level',
        ),
        migrations.RenameField(
            model_name='setupuser',
            old_name='organization',
            new_name='your_organization',
        ),
    ]
