# Generated by Django 2.0.3 on 2018-05-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkm_app', '0009_auto_20180507_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildkb',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='buildkb',
            name='upload',
            field=models.FileField(default=None, upload_to='./documents'),
        ),
        migrations.AlterField(
            model_name='buildkb',
            name='knowledge_category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
