# Generated by Django 2.0.3 on 2018-05-08 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkm_app', '0010_auto_20180508_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildkb',
            name='share_with',
        ),
        migrations.AddField(
            model_name='buildkb',
            name='share_with',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
