# Generated by Django 2.0.3 on 2018-05-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkm_app', '0011_auto_20180508_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildkb',
            name='upload',
        ),
    ]
