# Generated by Django 2.0.3 on 2018-05-16 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkm_app', '0013_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='fkey',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
